#+TAGS: noexport(n) software(s) Alexis(a) Florence(f) deprecated(d) EM(e) HMM(h) MMST(m) R(r) C(c)

#+Title: Journal
#+AUTHOR:      Steven QUINITO MASNADA
#+BABEL: :tangle yes :noweb yes

* TODO Objectives [1/9]
  - [ ] Create R package from Stephane Despreaux source code
  - [ ] Implement Markov field approach
  - [ ] Parallelization [0/5]
    - [ ] Find literature about Markov fields computation
      parallelization
    - [ ] Take a look at Stable/independent set \to Markov fields
      decomposition 
    - [ ] GPUs
    - [ ] Cluster
    - [ ] Is StarPU suited?
  - [-] Optimization [1/6]
    - [ ] Code refactoring
    - [ ] Code audit:
      - profiling \to Gprof
      - instrumenting \to PAPI or Likwid
    - [X] Is BOAST suited? Can we mix it with StarPU?
      Yes, but BOAST not suited for c++.
    - [ ] How to organize data in memory (row vs column) eg. [MRI x
      Observations] vs [Observations x MRI]
    - [ ] Use fixed size matrices/vectors
    - [ ] Use the right to type at the right place
  - [ ] Centralize Alexis's code and repo?
  - [ ] Ask Jaime about pyHRF
  - [X] Move =HMM_MMST.org= to Alexis's Gibbs project.
  - [-] Structure the repository using subrepo / submodule.
    - [X] Move repos outside the repo where the journal is
    - [ ] Use submodule
  - [-] A first running version
    - [X] C++ code as .so
      Using Rcpp to export and expose functions / classes to R.
    - [X] Split c++ source
    - [ ] Write test cases
    - [ ] Computation of the lower bounds
    - [ ] Computation of the log densities
    - [ ] Conditional compilation of openmp version
* Repository
  #+begin_src sh :results output :exports both
    # Gibbs MMST
    git clone https://stevenqm@scm.gforge.inria.fr/authscm/stevenqm/git/mmsdarticle/mmsdarticle.git
    git clone https://stevenqm@scm.gforge.inria.fr/authscm/stevenqm/git/mmsdarticle/article.git
    git clone https://stevenqm@scm.gforge.inria.fr/authscm/stevenqm/git/mmsdarticle/code.git

    git clone https://gitlab.inria.fr/arnaud/MMST_with_Markov_Random_Field.git

    git svn clone --username stevenqm https://scm.gforge.inria.fr/authscm/stevenqm/svn/ginria/ -s
    git svn clone --username stevenqm https://scm.gforge.inria.fr/authscm/stevenqm/svn/spacem3/ -s 
  #+end_src
* Tips
** Org mode
   - To format a text to fit 80 charac / line \to fill-paragraph or fill-region
* September
** 2017-09-05
*** Tumor detection process                                        :software:
    1. ROI localization
      a. Build the reference model of healthy subjects:
        - Find data cluster according to their distribution (multiple
        scale t-distributions) using the EM algorithm 
        - Aggregate these distributions into a mixture model
      b. Distriminate abnormal voxels:
        - By using reference model to compute likelyhood score for each
          voxels 
        - Determine a threshold to distinguish healthy from pathological
	  - Compute the different anomaly level thresholds using slope
            heuristic
	  - Compute threshold of only 2 components (healthy /
            pathological) and keep the closest to one of the threshold
            computed previously.
    2. Build a anomaly model:
       - same as in 1.a on abnormal voxels
    3. Fingerprint model \to Supervised learning to characterize the
       different tumor types:
       - Compute the proportion of each anomaly clusters in the tumors
       - Take into account their sizes.
    4. Remove healthy isolated voxels considered as abnormal.
       - Refined segmentation \to erosion-dilatation kernel to remove
         isolated voxels.
       - Refined fingerprint model \to redo 3. using refined segmentation
** 2017-09-11
*** EM algorithm explanation                                  :deprecated:EM:
    _*Update:* The EM algorithm has been studied and described with more detail_
    _in [[file:Notes.org][Notes.org]] and in [[file:HMM_MMST.org][HMM_MMST.org]]._

    In this case, the models used are t-distributions and the EM
    algorithm try to find the following parameters:
    - \mu \to mean of the distribution
    - D \to Covariance matrix \to orientation
    - A \to shape and volume
    - \nu \to degrees of freedom
    
    There are two steps:
    - Expectation \to compute posterior probabilities \to find latent variables
    - Maximization \to update parameter model by maximizing the log likelyhood
      \to find parameter values
            
* October
** 2017-10-20
*** Meeting
    - For parallelization take a look at independent set \to grid/graph
      partitioning, conditional independence + GPU + MRF
    - Ideally, the order for which we compute the label
      distribution (q_{z_n}) at each site should be randomized. This
      imply a different graph dependency at each iteration.
    - \beta \to Numerical optimization involves of sum above all the voxels
      \to costly \to take a look at stochastic gradient.
* November
** 2017-11-06
   - Considering the code, it seems a project is implemented by method
     (e.g baysian, HMM, etc...) maybe it should be better if
     everything is gathered in one project \to same code base.

   - At first we will start with a 2D neighbourhood because on rat MRI
     the resolution on the z-axis is low (only 5 vs 256). Indeed each slice
     of the z-axis is far form each others and in this case
     considering the neighbours in the z-axis seems not important
     because they are very far compared to the one on the x or
     y-axis. When moving to human MRI 3D neighbourhood will be necessary.
** 2017-11-13
*** TODO Meeting
**** DONE Algorithms
     Release a first implementation to see how it performs with
     possible code optimization and then we can think about maybe
     modifying the EM algorithm itself maybe with some approximations,
     etc...
**** DONE Code organization
     Use as a basis the Bayesian version, but without the bayesian part
     and include the HMM part to have quickly a version to test.
     Once implemented we will see if we include this to SpaceM^3 or to
     Stephane Despréaux package.
**** TODO Git repo organization
     - [ ] A git based work-flow
       https://hal.inria.fr/hal-01112795/file/SIGOPS_paper.pdf
** 2017-11-16
*** R call C/C++                                                        :R:C:
**** Dplyr example
     Dplyr use c++ so I just took it as an example just to check the compiler directives (include paths, etc...):
     #+begin_src R :results output :session :exports both
     install.packages("dplyr")
     #+end_src

     #+RESULTS:
     #+begin_example
     Installation du package dans ‘/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4’
     (car ‘lib’ n'est pas spécifié)
     essai de l'URL 'https://pbil.univ-lyon1.fr/CRAN/src/contrib/dplyr_0.7.4.tar.gz'
     Content type 'application/x-gzip' length 808054 bytes (789 KB)
     ==================================================
     downloaded 789 KB

     * installing *source* package ‘dplyr’ ...
     ** package ‘dplyr’ correctement décompressé et sommes MD5 vérifiées
     ** libs
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c address.cpp -o address.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c api.cpp -o api.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c arrange.cpp -o arrange.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c between.cpp -o between.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bind.cpp -o bind.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c combine_variables.cpp -o combine_variables.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c distinct.cpp -o distinct.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c encoding.cpp -o encoding.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c filter.cpp -o filter.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c group_by.cpp -o group_by.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c group_indices.cpp -o group_indices.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid.cpp -o hybrid.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_count.cpp -o hybrid_count.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_debug.cpp -o hybrid_debug.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_in.cpp -o hybrid_in.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_minmax.cpp -o hybrid_minmax.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_nth.cpp -o hybrid_nth.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_offset.cpp -o hybrid_offset.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_simple.cpp -o hybrid_simple.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hybrid_window.cpp -o hybrid_window.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.cpp -o init.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c join.cpp -o join.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c join_exports.cpp -o join_exports.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c mutate.cpp -o mutate.o
     gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rlang-export.c -o rlang-export.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c select.cpp -o select.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c set.cpp -o set.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c slice.cpp -o slice.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c summarise.cpp -o summarise.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c test.cpp -o test.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.cpp -o utils.o
     g++  -I/usr/share/R/include -DNDEBUG -I../inst/include -DCOMPILING_DPLYR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/BH/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/bindrcpp/include" -I"/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/plogr/include"    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c window.cpp -o window.o
     g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o dplyr.so RcppExports.o address.o api.o arrange.o between.o bind.o combine_variables.o distinct.o encoding.o filter.o group_by.o group_indices.o hybrid.o hybrid_count.o hybrid_debug.o hybrid_in.o hybrid_minmax.o hybrid_nth.o hybrid_offset.o hybrid_simple.o hybrid_window.o init.o join.o join_exports.o mutate.o rlang-export.o select.o set.o slice.o summarise.o test.o utils.o window.o -L/usr/lib/R/lib -lR
     installing to /home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/dplyr/libs
     ** R
     ** data
     *** moving datasets to lazyload DB
     ** inst
     ** preparing package for lazy loading
     ** help
     *** installing help indices
     *** copying figures
     ** building package indices
     ** installing vignettes
     ** testing if installed package can be loaded
     * DONE (dplyr)

     Les packages source téléchargés sont dans
             ‘/tmp/Rtmp1i7F52/downloaded_packages’
#+end_example
**** C source
***** Main
     #+BEGIN_SRC c :tangle ../../../other/R/C/src/core/main.c
       #include<stdio.h>
       #include<stdlib.h>

       #include"vectorAdd.h"

       #define LENGTH 8

       int main(int argc, char** argv){
           int a[LENGTH] = {1,2,3,4,5,6,7,8};
           int b[LENGTH] = {1,2,3,4,5,6,7,8};

           int c[LENGTH] = {0,0,0,0,0,0,0,0};

           vectorAdd(a,b,c,LENGTH);

           for(int i = 0; i < LENGTH; i++){
               printf("%d ", c[i]);
           }
           
           printf("\n");
           
           return EXIT_SUCCESS;
       }
     #+END_SRC
***** Header 
     #+BEGIN_SRC c :tangle ../../../other/R/C/src/core/vectorAdd.h
       void vectorAdd(const int* a, const int *b, int *c, const int length);
     #+END_SRC
***** function
     #+BEGIN_SRC c :tangle ../../../other/R/C/src/core/vectorAdd.cpp
       #include"vectorAdd.h"

       void vectorAdd(const int* a, const int *b, int *c, const int length){
           for(int i = 0; i < length; i++){
               c[i] = a[i] + b[i];
           }
       }
     #+END_SRC
***** Makefile
     #+BEGIN_SRC makefile :tangle ../../../other/R/C/src/core/Makefile
       CC=g++
       CFLAGS=-O3
       # INCLUDES=-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include -I/usr/share/R/include/
       INCLUDES=
       LIBS=-L/usr/lib/R/lib -lR

       vectorAdd.o: vectorAdd.cpp
       $(CC) $(CFLAGS) $(INCLUDES) -fPIC -c $^

       libvectoradd.so: vectorAdd.o
       $(CC) $(CFLAGS) -shared -o $@ $^ $(LIBS)

       main: main.c
       $(CC) $(CFLAGS) -o $@ $^ -L. -lvectoradd

       all: vectorAdd.o libvectoradd.so main

       clean:
       rm -f vectorAdd.o libvectoradd.so main

     #+END_SRC
***** Compile and run
      #+begin_src sh :results output :exports both
        cd ../../../other/R/C/src/core/
        make all
        export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
        ./main
      #+end_src
**** C wrapper
***** Manual
      Not sure R data structures stores elements are stored
      contiguously in memory and because I don't want to rely and R
      type, in the following example I use vector as a intermediary
      type to convert R variable type to C arrays. It is a little ugly
      maybe there exist a better way. Maybe using armadillo type could
      be the way to do...
      #+BEGIN_SRC c :tangle ../../../other/R/C/src/r_wrapper/wrapper.cpp
        // Extension to convert std::vector to SEXP
//        #include<RcppCommon.h>
//        namespace Rcpp{
//            namespace traits{
//                template <typename T> SEXP wrap(const std::vector<T> & obj);
//            }
//        }

        #include<Rcpp.h>
//        namespace Rcpp{
//            namespace traits{
//                template <typename T> SEXP wrap(const std::vector<T> & obj){
//                    const int RTYPE = Rcpp::traits::r_sexptype_traits<T>::rtype ;                    
//                    return Rcpp::Vector< RTYPE >(obj.begin(), obj.end());
//                };                
//            }
//        }
      
      #+END_SRC

      #+BEGIN_SRC c :tangle ../../../other/R/C/src/r_wrapper/wrapper.cpp
              
        #include<vector>
        #include"../core/vectorAdd.h"

        using namespace Rcpp;

        extern "C" SEXP addVectorWrapper(SEXP a, SEXP b, SEXP c, SEXP length){
            std::vector<int> a_ = Rcpp::as< std::vector<int> > (a);
            std::vector<int> b_ = Rcpp::as< std::vector<int> > (b);
            std::vector<int> c_ = Rcpp::as< std::vector<int> > (c);
            Rcpp::traits::input_parameter< int >::type length_(length);

            int* _a = &a_[0];
            int* _b = &b_[0];
            int* _c = &c_[0];
            std::vector<int> foo;
            vectorAdd(_a, _b, _c, length_);
            return Rcpp::wrap(c_);            
            // return R_NilValue;
        }
      #+END_SRC
***** Automatic
**** C shared library for R
     #+begin_src sh :results output :exports both
       cd /home/mistis/squinito/Dev/other/R/C/src/r_wrapper
       PKG_CPPFLAGS="-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" \
       PKG_LIBS="-L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp" \
       R CMD SHLIB ../core/vectorAdd.cpp wrapper.cpp
     #+end_src

**** R calling C
     #+begin_src R :results output :session :exports both
       library("Rcpp")
       setwd("/home/mistis/squinito/Dev/other/R/C/src/core")
       a = matrix(c(1,2,3,4),nrow=4,ncol=1)
       b = matrix(c(1,2,3,4),nrow=4,ncol=1)
       c = matrix(c(0,0,0,0),nrow=4,ncol=1)
       x <- dyn.load("vectorAdd.so")
       .Call("addVectorWrapper", a, b, c, 4)
       c
     #+end_src

     #+RESULTS:
     : 2
     : [1] 2 4 6 8
     :      [,1]
     : [1,]    0
     : [2,]    0
     : [3,]    0
     : [4,]    0


**** Rcpp
     - To crate a package using the specified c/c++ source files:
       #+begin_src R :results output :session :exports both
         Rcpp.package.skeleton(example_code=FALSE, cpp_files=c("src/vectorAdd.c", "src/vectorAdd.h"))
       #+end_src
       The package is create in different directory that the on
       specified. It is silly because it copies files instead of just
       turning the specified directory into a package.

     - Add c/c++ file references to RccExports.{R/cpp}
       #+begin_src R :results output :session :exports both
         compileAttributes(pkgdir="anRpackage/")
       #+end_src
**** Guideline
     - Never use abort or exit or any stuff that can call them because
       they kill the R process.
**** Expose classes
     #+BEGIN_SRC c++ :tangle ../../../other/R/C/expose_class/src/A.hpp
       #ifndef A_HPP
       #define A_HPP
       #include<Rcpp.h>

       using namespace Rcpp;

       class A{
       public:
           int x;

           A(int x);
           int foo();
       };      
       #endif
     #+END_SRC

     #+BEGIN_SRC c++ :tangle ../../../other/R/C/expose_class/src/A.cpp
       #include"A.hpp"

       A::A(int x): x(x) {}
       int A::foo(){ return x * x; }
     #+END_SRC

     #+BEGIN_SRC c++ :tangle ../../../other/R/C/expose_class/src/B.hpp
       #ifndef B_HPP
       #define B_HPP

       #include<Rcpp.h>
       #include"A.hpp"

       using namespace Rcpp;

       class B{
       public:
           A a;
           B(int x);
       };

       #endif
     #+END_SRC

     #+BEGIN_SRC c++ :tangle ../../../other/R/C/expose_class/src/B.cpp
       #include"B.hpp"

       B::B(int x): a(x){ } 
     #+END_SRC

     #+BEGIN_SRC c++ :tangle ../../../other/R/C/expose_class/src/RcppWrapper.cpp
       #include"A.hpp"
       #include"B.hpp"
       RCPP_EXPOSED_CLASS(A);
       RCPP_EXPOSED_CLASS(B);
       RCPP_MODULE(mod) {
           class_<A>( "A" )
               // Constructors :
               // .constructor( "default" )
               .constructor< int >( "sets x" )
               // Fields :
               .field( "x", &A::x, "Value of x")
               
               // Methods :
               .method( "foo", &A::foo, "access of the private field 'clusters'")
               ;
           class_<B>( "B" )
               // Constructors :
               // .constructor( "default" )
               .constructor< int >( "sets a" )
               // Fields :
               .field( "a", &B::a, "Value of a")
               
               // Methods :
               ;
       }      
     #+END_SRC

     #+begin_src sh :results output :exports both
       cd /home/mistis/squinito/Dev/other/R/C/expose_class/src
       PKG_CPPFLAGS="-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" \
       PKG_LIBS="-L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp" \
       R CMD SHLIB A.cpp B.cpp RcppWrapper.cpp -o libtest.so
     #+end_src

     #+RESULTS:
     : g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o libtest.so A.o B.o RcppWrapper.o -L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp -L/usr/lib/R/lib -lR

     #+begin_src R :results output :session :exports both
       library(Rcpp)
       setwd("/home/mistis/squinito/Dev/other/R/C/expose_class/src/")
       lib <- dyn.load("classes.so")
       mymodule <- Rcpp::Module("mod",lib)

       B <- mymodule$B
       b <- new( B, 4 )
       a <- b$a
       a$x
       a$foo()
     #+end_src

     #+RESULTS:
     : [1] 4
     : [1] 16

**** Export list
      When using a =std::list= or =std::vector= of a non-primitive
      c++ type in a public field of a class or in a method parameter
      Rcpp doesn't know how to convert the type. However if it is the
      return type of a method, it doesn't complain.
     #+BEGIN_SRC c++ :tangle /tmp/list.cpp
       #include<Rcpp.h>
             
       class A{
       public:
           int x;
           A(){}
           A(int x):x(x){}
       };

       class B{
       private:
           std::list< A > a_list;
       public:
           A a;
           B():a(10){ a_list.push_back(a); a_list.push_back(a);}
           void foo(std::list< A > l){}
           std::list< A > get_list(){return a_list;}
           void set_list(const std::list< int > l){}
       };

       RCPP_EXPOSED_CLASS(A);
       RCPP_EXPOSED_CLASS(B);

       RCPP_MODULE(mod) {
           using namespace Rcpp;
           class_<A>("A")
               .constructor()
               .constructor<int>()
               .field("x", &A::x, "blabla")
               ;
           class_<B>("B")
               .constructor()
               .field("a", &B::a, "blablabla")
               //.field("a_list", &B::a_list, "blablabla")
               .property("get_list", &B::get_list, "")
               //.method("foo", &B::foo, "blabla")
               ;
           class_< std::list< A > >("list")
               .constructor()
               .method("pop_back", &std::list< A >::pop_back, "")
               ;
       }
     #+END_SRC

     #+BEGIN_SRC makefile
       main: list.cpp
               PKG_CPPFLAGS="-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" \
               PKG_LIBS="-L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp" \
               R CMD SHLIB $^ -o liblist.so     
       clean:
               rm -f *.so *.o
     #+END_SRC

     #+begin_src sh :results output :exports both
       cd /tmp
       PKG_CPPFLAGS="-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" \
       PKG_LIBS="-L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp" \
       R CMD SHLIB list.cpp -o liblist.so

     #+end_src

     #+RESULTS:

     #+begin_src R :results output :exports both
       library(Rcpp)
       setwd("/tmp")
       lib <- dyn.load("list.so")
       mymod <- Rcpp::Module("mod", lib)
       B <- mymod$B
       b <- new(B)
       list <- b$get_list()
       list
     #+end_src

     #+RESULTS:
     : [[1]]
     : C++ object <0x1f4d890> of class 'A' <0x2a0d350>
     : 
     : [[2]]
     : C++ object <0x27ceac0> of class 'A' <0x2a0d350>
     : 

      In fact the problem is not =std::list/vector/whatever= but what it
      contains if we want to use it like this we need to tell R how to
      convert A.
     #+BEGIN_SRC c++ :tangle /tmp/RcppWrapper.cpp
       //#include<RcppCommon.h>

       class A{
       public:
           int x;
           A():x(10){}
           // A(const A& a):x(a.x){}
           // ~A(){}
           // A(SEXPREC *x){}
           //operator SEXP(){ return R_NilValue;}
       };

       /* namespace Rcpp{
           // R to C++
           template<> SEXP wrap(const A&);
           // C++ to R
           // template <> class Exporter< std::vector<A> >;
       } */

       #include<Rcpp.h>       

       RCPP_EXPOSED_CLASS(A);
       RCPP_EXPOSED_WRAP(A);
       RCPP_EXPOSED_AS(A);

       /* namespace Rcpp{
           // R to C++
           SEXP wrap(const A& obj){
               return R_NilValue;
           }
       } */

       extern "C" SEXP foo(SEXP x){
           std::list< A > x_ = Rcpp::as< std::list< A > > (x);
           return Rcpp::wrap(x_);
           //return R_NilValue;
       }
     #+END_SRC

      #+begin_src sh :results output :exports both
        cd /tmp
        PKG_CPPFLAGS="-I/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" \
        PKG_LIBS="-L/home/mistis/squinito/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/libs -lRcpp" \
        R CMD SHLIB RcppWrapper.cpp

      #+end_src

      #+RESULTS:

      #+begin_src R :results output :session :exports both
      
      #+end_src
** 2017-11-20
   How much more computation will we do if we add borders with virtual
   voxels to avoid if conditions?
    #+BEGIN_SRC ruby
      h = 256
      w = 256
      n_h = 1
      n_w = 1

      ######### Naive approach #########
      naive = 0

      # Borders
      sum = 0
      (0...(w - 2 * n_w)).each do
        (0...(n_h)).each do |j|
          sum += (2 * n_w + 1) * (n_h + 1 + j) - 2
        end
      end

      naive += 4 * sum

      # Corners
      sum = 0
      (0...(n_w)).each do |i|
        (0...(n_h)).each do |j|
          sum += (n_w + 1 + i) * (n_h + 1 + j) - 2
        end
      end

      naive += 4 * sum

      naive += (w - 2 * n_w) * (h - 2 * n_h) * ((2 * n_h + 1) * (2 * n_w + 1) - 2)

      ######### Virtual border approach #########
      virt = h * w * ((2 * n_h + 1) * (2 * n_w + 1) - 2)
      virt

      virt.to_f / naive.to_f
   #+END_SRC

    #+RESULTS:
    : 1.0067327358432598

   Small computation overhead \to less than 1% more 

* Emacs Setup 							   :noexport:
  This document has local variables in its postembule, which should
  allow Org-mode to work seamlessly without any setup. If you're
  uncomfortable using such variables, you can safely ignore them at
  startup. Exporting may require that you copy them in your .emacs.

# Local Variables:
# eval:    (require 'org-install)
# eval:    (org-babel-do-load-languages 'org-babel-load-languages '( (sh . t) (R . t) (perl . t) (ditaa . t) ))
# eval:    (setq org-confirm-babel-evaluate nil)
# eval:    (unless (boundp 'org-latex-classes) (setq org-latex-classes nil))
# eval:    (add-to-list 'org-latex-classes '("memoir" "\\documentclass[smallextended]{memoir} \n \[NO-DEFAULT-PACKAGES]\n \[EXTRA]\n  \\usepackage{graphicx}\n  \\usepackage{hyperref}" ("\\chapter{%s}" . "\\chapter*{%s}") ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}")                       ("\\subsubsection{%s}" . "\\subsubsection*{%s}")                       ("\\paragraph{%s}" . "\\paragraph*{%s}")                       ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:    (add-to-list 'org-latex-classes '("acm-proc-article-sp" "\\documentclass{acm_proc_article-sp}\n \[NO-DEFAULT-PACKAGES]\n \[EXTRA]\n"  ("\\section{%s}" . "\\section*{%s}") ("\\subsection{%s}" . "\\subsection*{%s}")                       ("\\subsubsection{%s}" . "\\subsubsection*{%s}")                       ("\\paragraph{%s}" . "\\paragraph*{%s}")                       ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
# eval:    (setq org-alphabetical-lists t)
# eval:    (setq org-src-fontify-natively t)
# eval:   (setq org-export-babel-evaluate nil)
# eval:   (setq ispell-local-dictionary "english")
# eval:   (eval (flyspell-mode t))
# eval:    (setq org-latex-listings 'minted)
# eval:    (setq org-latex-minted-options '(("bgcolor" "white") ("style" "tango") ("numbers" "left") ("numbersep" "5pt")))
# End:
